import type { EventRecord } from "./types";

/**
 * Event catalogue. Legacy copy is preserved verbatim; the two new entries
 * (UAV Workshop, Weekly Group Discussion) are flagged `draft: true` where the
 * copy is placeholder awaiting ELSOC's final wording.
 */
export const events: EventRecord[] = [
  // ── Upcoming ────────────────────────────────────────────────────────────
  {
    slug: "sparkathon-2026",
    title: "Sparkathon",
    description:
      "A hackathon-style technical competition where participants solve real-world engineering problems and build innovative solutions.",
    category: "Competition",
    location: "Mini Auditorium",
    coverImage: "/img/events/sparkathon-banner.jpeg",
    startAt: "2026-09-15T10:00:00+05:30",
    endAt: "2026-09-15T18:00:00+05:30",
    dateLabel: "Sept, 2026 (Tentative)",
    timeLabel: "10:00 AM - 6:00 PM (Tentative)",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "UPCOMING",
    registrationLink: null,
    participants: "Open to All",
    highlights: ["₹19,000+ Prize Pool", "Networking Opportunities", "Skill Development"],
    featured: true,
    draft: false,
    sortOrder: 0,
  },
  {
    slug: "uav-workshop-2026",
    title: "UAV Workshop",
    description:
      "Hands-on workshop on unmanned aerial vehicles: flight dynamics, electronic speed controllers, flight-controller programming and a live assembly-and-fly session guided by the ELSOC technical team.",
    category: "Workshop",
    location: "NIT Hamirpur",
    coverImage: null, // PlaceholderMedia renders a branded skeleton until ELSOC uploads imagery
    startAt: null,
    endAt: null,
    dateLabel: "August 2026 (Date TBD)",
    timeLabel: "To be announced",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "UPCOMING",
    registrationLink: "#",
    participants: "Open to All",
    highlights: ["Live Drone Assembly", "Flight Controller Basics", "Hands-on Session"],
    featured: true,
    draft: true,
    sortOrder: 1,
  },
  {
    slug: "weekly-group-discussion",
    title: "Weekly Group Discussion",
    description:
      "ELSOC's recurring open-floor discussion where members dissect a technical topic, a research paper, or an industry trend — sharpening communication skills and technical depth in equal measure. Every Friday, everyone is welcome.",
    category: "Discussion",
    location: "Electrical Engineering Department",
    coverImage: null,
    startAt: null,
    endAt: null,
    dateLabel: "Every Friday",
    timeLabel: "6:00 PM",
    recurrence: "WEEKLY",
    dayOfWeek: "FRIDAY",
    status: "UPCOMING",
    registrationLink: null,
    participants: "All Members",
    highlights: ["Recurring", "Open Floor", "Soft Skills"],
    featured: false,
    draft: true,
    sortOrder: 2,
  },

  // ── Past ────────────────────────────────────────────────────────────────
  {
    slug: "ai-emma-robot-workshop",
    title: "Workshop #1 - AI-emma Robot",
    description:
      "Comprehensive hands-on workshop covering Robotics fundamentals, electrical project simulations, and practical applications for engineering students.",
    category: "Workshop",
    location: "Mini Auditorium",
    coverImage: "/img/events/ai-emma-workshop.jpg",
    startAt: "2025-11-12T16:00:00+05:30",
    endAt: "2025-11-12T19:00:00+05:30",
    dateLabel: "November 12, 2025",
    timeLabel: "4:00 PM - 7:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 10,
  },
  {
    slug: "techletics-2024",
    title: "TECHLETICS (OJAS X ELSOC)",
    description:
      "Thrilling fusion of innovation and competition featuring technical challenges, robotics demonstrations, and collaborative engineering projects.",
    category: "Competition",
    location: "SAC, NIT Hamirpur",
    coverImage: "/img/events/techletics.png",
    startAt: "2024-04-10T17:00:00+05:30",
    endAt: null,
    dateLabel: "April 10, 2024",
    timeLabel: "5:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 11,
  },
  {
    slug: "circuits-of-opportunities",
    title: "Circuits of Opportunities Workshop",
    description:
      "Career guidance workshop exploring diverse opportunities in finance, civil services, IT, core engineering, and defence sectors.",
    category: "Workshop",
    location: "LH G2, NIT Hamirpur",
    coverImage: null,
    startAt: "2023-10-18T17:00:00+05:30",
    endAt: null,
    dateLabel: "October 18, 2023",
    timeLabel: "5:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 12,
  },
  {
    slug: "kuizz-i-thon-2023",
    title: "KUIZZ-i-THON",
    description:
      "Technical quiz competition covering general science, space exploration, history of engineering, and current affairs.",
    category: "Competition",
    location: "LH G2, NIT Hamirpur",
    coverImage: "/img/events/kuizzithon.png",
    startAt: "2023-09-01T17:30:00+05:30",
    endAt: null,
    dateLabel: "September 1, 2023",
    timeLabel: "5:30 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 13,
  },
  {
    slug: "lightning-unleashed-2023",
    title: "Lightning Unleashed (ELSOC X OJAS)",
    description:
      "Collaborative event showcasing high-voltage demonstrations including insulation breakdown, corona discharge, power transformers, earth testing, and transformer limbs.",
    category: "Exhibition",
    location: "Electrical Department, NIT Hamirpur",
    coverImage: "/img/events/lightning-unleashed.jpeg",
    startAt: "2023-02-10T17:00:00+05:30",
    endAt: null,
    dateLabel: "February 10, 2023",
    timeLabel: "5:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 14,
  },
  {
    slug: "matlab-workshop-2022",
    title: "MATLAB Workshop",
    description:
      "Programming platform workshop designed for engineers and scientists to analyze systems, design products, and create solutions using MATLAB simulations.",
    category: "Workshop",
    location: "NEW-LH, NIT Hamirpur",
    coverImage: "/img/events/matlab-workshop.jpeg",
    startAt: "2022-10-21T16:00:00+05:30",
    endAt: "2022-10-21T18:00:00+05:30",
    dateLabel: "October 21, 2022",
    timeLabel: "4:00 PM - 6:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 15,
  },
  {
    slug: "intern-talk-research-internships",
    title: "Intern Talk - Research Internships",
    description:
      "Inspiring session with ELSOC members sharing their research internship experiences at DRDO, RWTH Aachen Germany, NTU Singapore, TU Darmstadt, and IISc Bangalore.",
    category: "Seminar",
    location: "Auditorium, NIT Hamirpur",
    coverImage: "/img/events/guest-lecture.jpg",
    startAt: "2022-08-29T18:00:00+05:30",
    endAt: null,
    dateLabel: "August 29, 2022",
    timeLabel: "6:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 16,
  },
  {
    slug: "blockchain-workshop-2022",
    title: "Blockchain Workshop",
    description:
      "Interactive online workshop on blockchain technology and cryptocurrency fundamentals, featuring a live quiz competition.",
    category: "Workshop",
    location: "YouTube Live",
    coverImage: "/img/events/blockchain-workshop.png",
    startAt: "2022-02-04T15:00:00+05:30",
    endAt: null,
    dateLabel: "February 4, 2022",
    timeLabel: "3:00 PM",
    recurrence: "NONE",
    dayOfWeek: null,
    status: "COMPLETED",
    registrationLink: null,
    participants: null,
    highlights: [],
    featured: false,
    draft: false,
    sortOrder: 17,
  },
];
