import type { ProjectRecord } from "./types";

/**
 * Project portfolio.
 *
 * Records 1–5 are the Team OJAS "Final Five" (2026 cycle), integrated from the
 * approved proposal document; their abstracts are professional flowing prose
 * adapted from the signed proposals. Records 6–13 are the legacy showcase
 * carried over from the previous site.
 */
export const projects: ProjectRecord[] = [
  // ── Team OJAS — Final Five (2026) ───────────────────────────────────────
  {
    slug: "ert-landslide-alert-system",
    title: "ERT-Based Landslide Alert System",
    summary:
      "A low-cost, permanently installed Electrical Resistivity Tomography network that builds a real-time health map of hillsides and raises early landslide warnings.",
    abstract: [
      "This project addresses the large-scale problem of landslides in hilly regions, where heavy rainfall quietly weakens slopes from within and can suddenly cause massive damage to roads, villages, and infrastructure. The solution is a low-cost, permanently installed monitoring system that sends small electrical signals into the ground and observes how the soil responds — a response that changes as the slope becomes more water-logged and prone to failure. Using a microcontroller-based, modular design built around ready-made electronic boards, the system avoids complex lab-style circuits and can be easily expanded to cover long stretches of hillside with many electrodes.",
      "Each unit operates automatically and sends its data wirelessly to an online platform, helping create a real-time “health map” of the underground condition of slopes over large areas. Authorities and disaster-management teams receive early warnings when slope conditions become dangerous, enabling timely evacuation, maintenance, and planning — ultimately reducing loss of life and economic damage on a regional scale.",
      "Where current commercial resistivity meters cost upwards of ₹5–10 lakhs, are bulky, and require manual operation, this system takes a fundamentally different approach: an ESP32-based design with high-precision signal-generation, sensing, and multiplexing modules and built-in IoT connectivity. The result is reliable, easy to replicate, and scalable into dense networks of permanent monitoring nodes on vulnerable hillsides.",
    ].join("\n\n"),
    category: "IoT",
    coverImage: null,
    technologies: [
      "ESP32-WROOM-32",
      "AD9833 DDS Signal Generator",
      "INA219 Current Monitor",
      "CD74HC4067 Multiplexer",
      "ADS1115 16-bit ADC",
      "AD620 Instrumentation Amplifier",
      "Electrical Resistivity Tomography",
      "IoT Telemetry",
    ],
    team: ["Ronak Dotasara"],
    facultyCoordinator: "Dr. Katam Nishanth",
    year: "2026",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: true,
    draft: false,
    sortOrder: 0,
  },
  {
    slug: "self-sustaining-electric-crop-harvester",
    title: "Self-Sustaining Electric Crop Harvester with Innovative Stubble Handling",
    summary:
      "An electric harvester that burns crop stubble in a filtered closed chamber and converts the heat into drive power through thermoelectric generators — no stubble left on the field.",
    abstract: [
      "This project introduces an innovative self-sustaining electrical agriculture vehicle designed to address the critical environmental challenge of stubble burning. Every year, farmers burn crop residue to clear fields for new sowing — a practice that triggers a severe smog crisis in urban centres like Delhi, driven by the logistical cost of transporting bulky waste. The proposed solution integrates harvesting and waste management into a single, mobile platform.",
      "During harvesting, crop residue is fed into an internal combustion chamber where Thermoelectric Generator (TEG) modules convert the generated heat directly into electricity that drives the harvester itself. To ensure environmental safety, a specialized exhaust chamber equipped with HEPA and activated-carbon filters removes smoke and toxic gases before atmospheric release, and the collected soot is repurposed to manufacture ink — adding a secondary value stream. With an average temperature difference of around 152 °C across the TEG cells during operation, each cell contributes roughly 4.2 W; combined with battery storage and solar support, the recovered energy meaningfully offsets the harvester's power requirement.",
      "By transforming a waste product into a primary power source, the technology offers a clean, green, and instantaneous alternative to traditional stubble handling — leaving no stubble on the field while existing approaches (Happy Seeders, bio-decomposers, or collection for power plants) remain slow, logistics-heavy, or partial.",
    ].join("\n\n"),
    category: "Power Systems",
    coverImage: null,
    technologies: [
      "SP1848 Thermoelectric Generators",
      "ESP32",
      "L298N Motor Driver",
      "HEPA + Activated Carbon Filtration",
      "Servo Actuation",
      "LiPo Power System",
    ],
    team: ["Sojal", "Vansh Kumar Gautam"],
    facultyCoordinator: "Dr. Katam Nishanth",
    year: "2026",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: true,
    draft: false,
    sortOrder: 1,
  },
  {
    slug: "ultrasonic-parametric-audio-system",
    title: "Ultrasonic Parametric Audio System: Invisible Airborne Speaker",
    summary:
      "A parametric ultrasonic array that beams audio which becomes audible only at the target location — directional sound with no headphones and no leakage.",
    abstract: [
      "Conventional loudspeakers radiate sound omnidirectionally, leading to noise pollution and a lack of audio privacy in public environments. This project presents an Invisible Air Speaker based on a parametric ultrasonic array, in which audible sound is transmitted through amplitude modulation of a 40 kHz ultrasonic carrier generated and controlled by an ESP32 microcontroller. The modulated signal is amplified through a gate-driver-based MOSFET power stage and radiated by a 4×4 array of Murata MA40S4S ultrasonic transducers.",
      "Due to the nonlinear acoustic properties of air, the ultrasonic beam self-demodulates into audible sound only at the target location, enabling highly directional audio delivery — visitors hear the audio only at a marked position. According to guidelines from the World Health Organization, Health Canada, and IEEE, airborne ultrasonic exposure at the operating frequency and sound pressure levels used in this project (80–95 dB SPL at 40 kHz, well below the 120 dB safety threshold) is considered safe for humans and animals under controlled conditions.",
      "Where typical commercial directional speakers cost ₹50,000–70,000, the complete prototype comes in under ₹10,000, with a modular array design that scales from a single 4×4 unit to larger N×N configurations. The system offers an innovative, compact, and energy-efficient solution for museums and exhibitions, smart advertising kiosks, silent zones such as libraries, and immersive AR/VR audio — demonstrating the feasibility of safe directional sound technology for academic and practical use.",
    ].join("\n\n"),
    category: "Embedded",
    coverImage: null,
    technologies: [
      "ESP32-WROOM-32",
      "Murata MA40S4S Transducer Array",
      "IR2110 Gate Drivers",
      "MOSFET H-Bridge",
      "Amplitude Modulation @ 40 kHz",
      "Parametric Acoustics",
    ],
    team: ["Skandh Nagar"],
    facultyCoordinator: "Dr. Katam Nishanth",
    year: "2026",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: true,
    draft: false,
    sortOrder: 2,
  },
  {
    slug: "switchgear-condition-monitoring",
    title: "Condition-Based Monitoring of Switchgear",
    summary:
      "An IoT-enabled miniature switchgear prototype that watches temperature, humidity, vibration and acoustic signatures 24/7 to predict and prevent panel fires.",
    abstract: [
      "Switchgear panels are critical components in electrical distribution systems, yet they are prone to catastrophic fires due to overheating, insulation degradation, partial discharges, and condensation from high humidity. Traditional preventive maintenance is periodic and often ineffective at detecting incipient faults, resulting in unplanned downtime and safety risks. This project presents a low-cost, IoT-enabled condition-based monitoring prototype designed to predict and prevent fires in low-voltage switchgear cubicles.",
      "The prototype is constructed as a compact miniature low-voltage switchgear model within a safe enclosure, featuring copper busbars, a DIN-rail-mounted main breaker and feeder MCBs, and high-power resistors to simulate hotspots. An ESP32 microcontroller continuously acquires data from strategically placed sensors — DS18B20 probes at busbars and breaker terminals for temperature, a DHT22 for enclosure humidity, an HC-SR04 ultrasonic sensor for partial-discharge acoustic simulation, and an MPU6050 for vibration. Threshold logic drives escalating alerts: yellow LEDs and a soft buzzer for warnings, and red LEDs, a loud siren, and an automatic relay trip (with fan-based suppression simulation) for critical conditions. All data and alarm states stream over Wi-Fi to an IoT dashboard for remote monitoring, trend viewing, and instant push notifications.",
      "Unlike reactive fire-suppression systems that act only after ignition, arc-resistant designs limited to premium new installations, or labour-intensive time-based inspections, this approach delivers autonomous 24/7 proactive monitoring of key fire precursors, retrofits without downtime, and shifts maintenance to condition-triggered action. The MQTT-based architecture extends naturally to multi-cubicle substation monitoring and adapts to transformers, motors, or cables with minor sensor changes.",
    ].join("\n\n"),
    category: "Power Systems",
    coverImage: null,
    technologies: [
      "ESP32",
      "DS18B20 Temperature Sensors",
      "DHT22 Humidity Sensor",
      "HC-SR04 Ultrasonic Sensor",
      "MPU6050 Vibration Sensing",
      "ACS712 Current Sensors",
      "MQTT / IoT Dashboard",
    ],
    team: ["Shivansh"],
    facultyCoordinator: "Dr. Katam Nishanth",
    year: "2026",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: true,
    draft: false,
    sortOrder: 3,
  },
  {
    slug: "intelligent-pesticide-sprinkling-system",
    title: "Intelligent Pesticide Sprinkling System",
    summary:
      "An edge-AI precision-agriculture rig: a Raspberry Pi CNN diagnoses plant disease on-site and an ESP32 sprays pesticide only where it is needed — cutting chemical use by up to 90%.",
    abstract: [
      "The core challenge in modern agriculture lies in the inefficiency of traditional “blind” pesticide application, which leads to substantial chemical waste, environmental degradation, and high operational costs. This project introduces an automated, data-driven framework designed to optimize pest management through precision agriculture and real-time diagnostic intelligence. By integrating an edge-computing architecture — a Raspberry Pi Zero W running a Convolutional Neural Network — the system performs on-site plant pathology to detect specific diseases and quantify infection severity.",
      "The innovation lies in the transition from broadcast spraying to a targeted, IoT-driven delivery mechanism. High-resolution foliage images and readings from an NPK + pH sensor suite feed the localized CNN, which determines the required chemical dosage. Diagnostic triggers travel over MQTT to an ESP32, which activates a 12 V diaphragm pump and relay system to deliver a precise pesticide spray only to the identified infected zones, while a cloud-linked React/Flutter dashboard provides real-time telemetry and manual override.",
      "The system is applicable from small home gardens to large-scale industrial farms: the MQTT framework lets a single central controller manage many distributed spray actuators, the diagnostic model can be retrained for diverse crop species, and the low-power hardware supports expansion into remote, solar-powered agricultural zones. Current literature reports CNN disease-detection accuracies above 95% and validates that edge computing eliminates the latency issues of cloud-dependent systems in rural areas — positioning this framework to reduce chemical usage by up to 90% while improving overall crop yield.",
    ].join("\n\n"),
    category: "IoT",
    coverImage: null,
    technologies: [
      "Raspberry Pi Zero W",
      "Convolutional Neural Network",
      "Pi Camera (8MP)",
      "NPK + pH Soil Sensor",
      "ESP32",
      "MQTT",
      "12V Diaphragm Pump",
      "React / Flutter Dashboard",
    ],
    team: ["Ronak Dotasara"],
    facultyCoordinator: "Dr. Katam Nishanth",
    year: "2026",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: true,
    draft: false,
    sortOrder: 4,
  },

  // ── Legacy showcase (carried over from the previous site) ───────────────
  {
    slug: "smart-home-automation-system",
    title: "Smart Home Automation System",
    summary:
      "Voice-controlled ESP32 home automation with Alexa and mobile-app integration plus real-time energy monitoring.",
    abstract:
      "Advanced IoT-based home automation using ESP32 microcontroller, enabling voice control through Alexa and mobile app integration for controlling lights, fans, appliances, and monitoring energy consumption in real-time.",
    category: "IoT",
    coverImage: "/img/projects/smart-home-automation.png",
    technologies: ["ESP32", "Arduino IDE", "MQTT Protocol", "Node-RED", "Alexa Integration"],
    team: ["Rohan Verma", "Sneha Patel", "Amit Kumar"],
    facultyCoordinator: null,
    year: "2025",
    workStatus: "Completed",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 10,
  },
  {
    slug: "autonomous-line-following-robot",
    title: "Autonomous Line Following Robot",
    summary:
      "PID-controlled autonomous robot that follows coloured lines with obstacle avoidance and adaptive speed control.",
    abstract:
      "Intelligent autonomous robot with advanced PID control algorithm, capable of detecting and following colored lines with high precision. Features include obstacle avoidance using ultrasonic sensors and adaptive speed control.",
    category: "Robotics",
    coverImage: "/img/projects/line-following-robot.avif",
    technologies: ["Arduino Uno", "IR Sensors Array", "L298N Motor Driver", "PID Controller"],
    team: ["Priya Sharma", "Karan Singh"],
    facultyCoordinator: null,
    year: "2024",
    workStatus: "Completed",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 11,
  },
  {
    slug: "solar-power-monitoring-system",
    title: "Solar Power Monitoring System",
    summary:
      "Cloud-logged real-time monitoring of solar panel efficiency with predictive analytics for maintenance.",
    abstract:
      "Comprehensive real-time monitoring and analysis system for solar panel efficiency with cloud-based data logging. Tracks voltage, current, power output, and environmental conditions with predictive analytics for maintenance.",
    category: "Power Systems",
    coverImage: "/img/projects/solar-power-monitoring.jpg",
    technologies: [
      "Raspberry Pi",
      "ACS712 Current Sensor",
      "Python",
      "ThingSpeak IoT",
      "Data Analytics",
    ],
    team: ["Anjali Gupta", "Vikram Reddy", "Sanjay Mehta"],
    facultyCoordinator: null,
    year: "2025",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 12,
  },
  {
    slug: "gesture-controlled-car",
    title: "Gesture Controlled Car",
    summary:
      "A glove-mounted accelerometer drives this RF-controlled car through intuitive hand movements.",
    abstract:
      "Innovative gesture-controlled car using accelerometer and gyroscope sensors mounted on a glove. Hand movements control car direction wirelessly through RF communication, enabling intuitive hands-free operation.",
    category: "Embedded",
    coverImage: "/img/projects/gesture-controlled-car.png",
    technologies: [
      "Arduino Nano",
      "MPU6050 Accelerometer",
      "RF Transceiver",
      "DC Motors",
      "Motor Driver",
    ],
    team: ["Neha Kapoor", "Rahul Joshi"],
    facultyCoordinator: null,
    year: "2024",
    workStatus: "Completed",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 13,
  },
  {
    slug: "industrial-automation-plc-system",
    title: "Industrial Automation PLC System",
    summary:
      "Professional PLC automation with a SCADA interface for real-time industrial monitoring and control.",
    abstract:
      "Professional-grade Programmable Logic Controller based automation system for industrial manufacturing processes. Features SCADA interface for real-time monitoring, control, and data visualization with alarm management.",
    category: "Automation",
    coverImage: "/img/projects/industrial-plc-automation.webp",
    technologies: [
      "Allen-Bradley PLC",
      "SCADA Software",
      "Ladder Logic Programming",
      "HMI Touch Panel",
    ],
    team: ["Arjun Malhotra", "Pooja Nair", "Deepak Kumar"],
    facultyCoordinator: null,
    year: "2025",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 14,
  },
  {
    slug: "weather-monitoring-station",
    title: "Weather Monitoring Station",
    summary:
      "IoT weather station logging temperature, humidity, pressure and air quality to a cloud dashboard.",
    abstract:
      "Comprehensive IoT weather station measuring temperature, humidity, atmospheric pressure, and air quality index. Data is logged to cloud platform with web dashboard for visualization and historical analysis.",
    category: "IoT",
    coverImage: "/img/projects/weather-monitoring-station.jpg",
    technologies: ["ESP8266", "DHT22 Sensor", "BMP180 Barometer", "MQ135 Air Quality", "ThingSpeak"],
    team: ["Ritika Sharma", "Varun Singh"],
    facultyCoordinator: null,
    year: "2024",
    workStatus: "Completed",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 15,
  },
  {
    slug: "smart-energy-meter",
    title: "Smart Energy Meter",
    summary:
      "GSM-connected digital energy meter with remote monitoring, theft detection and SMS alerts.",
    abstract:
      "Digital energy meter with GSM/GPRS communication for remote monitoring and automated billing system. Measures real-time power consumption, detects theft, and sends SMS alerts for anomalies.",
    category: "Embedded",
    coverImage: "/img/projects/smart-energy-meter.jpeg",
    technologies: [
      "Arduino Mega",
      "GSM SIM800L Module",
      "ACS712 Current Sensor",
      "16x2 LCD Display",
    ],
    team: ["Kavita Rao", "Manish Tiwari"],
    facultyCoordinator: null,
    year: "2024",
    workStatus: "Completed",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 16,
  },
  {
    slug: "fire-detection-alert-system",
    title: "Fire Detection & Alert System",
    summary:
      "Multi-sensor fire detection with automatic extinguisher activation and GPS-tagged mobile alerts.",
    abstract:
      "Intelligent fire detection system using multiple sensors (smoke, temperature, flame) with automatic fire extinguisher activation. Sends real-time alerts via SMS and mobile app with GPS location.",
    category: "IoT",
    coverImage: "/img/projects/fire-detection-system.jpg",
    technologies: ["ESP32", "MQ-2 Smoke Sensor", "Flame Sensor", "GSM Module", "Servo Motor"],
    team: ["Aditya Raj", "Meera Iyer"],
    facultyCoordinator: null,
    year: "2025",
    workStatus: "In Progress",
    status: "PUBLISHED",
    featured: false,
    draft: false,
    sortOrder: 17,
  },
];

export const projectCategories = [
  "All",
  "IoT",
  "Robotics",
  "Power Systems",
  "Embedded",
  "Automation",
] as const;
