import type { TeamMemberRecord } from "./types";

/**
 * Full ELSOC roster, carried over verbatim from the previous site.
 * `committee: true` marks Sparkathon organizing committee members.
 */
export const teamMembers: TeamMemberRecord[] = [
  // ── Faculty mentors ─────────────────────────────────────────────────────
  {
    name: "Dr. OP Rahi",
    position: "HOD, EED",
    group: "FACULTY",
    department: "Electrical Engineering Department",
    yearLabel: null,
    bio: "Guiding innovation with decades of expertise, Dr. Rahi inspires students to push boundaries and achieve excellence in electrical engineering research and education.",
    email: "oprahi@nith.ac.in",
    photo: "/img/faculty/op-rahi.png",
    linkedin: null,
    github: null,
    committee: false,
    draft: false,
    sortOrder: 0,
  },
  {
    name: "Dr. Bharti Bakshi Koul",
    position: "Coordinator, ELSOC",
    group: "FACULTY",
    department: "Electrical Engineering Department",
    yearLabel: null,
    bio: "Dedicated to nurturing young talent, Dr. Koul mentors ELSOC members with passion, fostering creativity, leadership, and technical excellence in every initiative.",
    email: "bhartibakshi@nith.ac.in",
    photo: "/img/faculty/bharti-bakshi-koul.jpg",
    linkedin: null,
    github: null,
    committee: true,
    draft: false,
    sortOrder: 1,
  },
  {
    name: "Dr. Katam Nishanth",
    position: "Coordinator, ELSOC",
    group: "FACULTY",
    department: "Electrical Engineering Department",
    yearLabel: null,
    bio: "With a focus on research and development, Dr. Nishanth guides students in exploring emerging technologies and developing solutions for real-world challenges.",
    email: "katam@nith.ac.in",
    photo: "/img/faculty/katam-nishanth.jpg",
    linkedin: null,
    github: null,
    committee: true,
    draft: false,
    sortOrder: 2,
  },
  {
    name: "Dr. Chandrasekaran S",
    position: "Coordinator, ELSOC",
    group: "FACULTY",
    department: "Electrical Engineering Department",
    yearLabel: null,
    bio: "Committed to advancing student learning, Dr. Chandrasekaran encourages innovation and practical application of electrical engineering concepts through hands-on projects.",
    email: "chandru@nith.ac.in",
    photo: "/img/faculty/chandrasekaran-s.jpg",
    linkedin: null,
    github: null,
    committee: true,
    draft: false,
    sortOrder: 3,
  },

  // ── Core team (final year) ──────────────────────────────────────────────
  {
    name: "Pratibha Bajia",
    position: "President",
    group: "CORE",
    department: null,
    yearLabel: "Final Year",
    bio: "Leading ELSOC with a vision for innovation and technical excellence.",
    email: null,
    photo: "/img/team/pratibha-bajia.jpg",
    linkedin:
      "https://www.linkedin.com/in/pratibha-bajia-62b3a12b1?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/Pratibha100",
    committee: true,
    draft: false,
    sortOrder: 0,
  },
  {
    name: "Nitin",
    position: "Vice-President",
    group: "CORE",
    department: null,
    yearLabel: "Final Year",
    bio: "Driving technical initiatives and fostering collaborative learning.",
    email: null,
    photo: "/img/team/nitin.jpg",
    linkedin:
      "https://www.linkedin.com/in/nitin-21767a2a7?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=ios_app",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 1,
  },
  {
    name: "Mohit Kumar",
    position: "Finance Secretary",
    group: "CORE",
    department: null,
    yearLabel: "Final Year",
    bio: "Finance Secretary, managing ELSOC's resources and budgeting for impactful projects and events.",
    email: null,
    photo: "/img/team/mohit-kumar.jpg",
    linkedin: null,
    github: null,
    committee: true,
    draft: false,
    sortOrder: 2,
  },
  {
    name: "Kriti Benjwal",
    position: "Media and Marketing Head",
    group: "CORE",
    department: null,
    yearLabel: "Final Year",
    bio: "Media and Marketing Head, promoting ELSOC's initiatives and engaging with the student community.",
    email: null,
    photo: "/img/team/kriti-benjwal.webp",
    linkedin:
      "https://www.linkedin.com/in/kriti-benjwal-b82864290?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 3,
  },
  {
    name: "Sahil Jaswal",
    position: "Technical and Event Organisation Head",
    group: "CORE",
    department: null,
    yearLabel: "Final Year",
    bio: "Organizing and managing the society's functions and communications.",
    email: null,
    photo: "/img/team/sahil-jaswal.png",
    linkedin:
      "https://www.linkedin.com/in/sahil-jaswal-250a51318?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/SahilJaswal709",
    committee: true,
    draft: false,
    sortOrder: 4,
  },

  // ── Third-year team ─────────────────────────────────────────────────────
  {
    name: "Ronak Dotasara",
    position: "General Secretary",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/ronak-dotasara.webp",
    linkedin: null,
    github: null,
    committee: true,
    draft: false,
    sortOrder: 0,
  },
  {
    name: "Vikalp Chaudhary",
    position: "Joint Secretary",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/vikalp-chaudhary.jpg",
    linkedin:
      "https://www.linkedin.com/in/vikalp-chaudhary-581287345?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 1,
  },
  {
    name: "Priya",
    position: "Media and Marketing Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/priya.png",
    linkedin:
      "https://www.linkedin.com/in/priya-ghangas-54a95338a?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 2,
  },
  {
    name: "Sanyam Vats",
    position: "Project Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/sanyam-vats.jpg",
    linkedin:
      "https://www.linkedin.com/in/sanyam-vats-5899b4270?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/sanyamvats",
    committee: true,
    draft: false,
    sortOrder: 3,
  },
  {
    name: "Vikas Kumar",
    position: "Design Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/vikas-kumar.jpg",
    linkedin:
      "https://www.linkedin.com/in/vikas-kumar-656798335?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 4,
  },
  {
    name: "Aryan Dhaka",
    position: "Technical Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/aryan-dhaka.jpg",
    linkedin:
      "https://www.linkedin.com/in/aryan-dhaka-20635b324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 5,
  },
  {
    name: "Riya Choudhary",
    position: "Content Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/riya-choudhary.jpg",
    linkedin:
      "https://www.linkedin.com/in/riya-choudhary-0882a230b?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/riyachoudhary06",
    committee: true,
    draft: false,
    sortOrder: 6,
  },
  {
    name: "Skand Nagar",
    position: "Event Organisation Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/skandh-nagar.jpg",
    linkedin: "https://www.linkedin.com/in/skandh-nagar-73b18a312/",
    github: null,
    committee: true,
    draft: false,
    sortOrder: 7,
  },
  {
    name: "Akshit Vardhan",
    position: "Finance Coordinator",
    group: "THIRD_YEAR",
    department: null,
    yearLabel: "3rd Year",
    bio: null,
    email: null,
    photo: "/img/team/akshit-vardhan.jpg",
    linkedin:
      "https://www.linkedin.com/in/akshit-vardhan-6b290a324?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
    github: "https://github.com/akshitvardhan",
    committee: true,
    draft: false,
    sortOrder: 8,
  },

  // ── Executive members (first year) ──────────────────────────────────────
  ...(
    [
      {
        name: "Akriti Mall",
        photo: "/img/team/akriti-mall.jpg",
        linkedin: null,
        github: null,
      },
      {
        name: "Ansh Bishnoi",
        photo: "/img/team/ansh-bishnoi.webp",
        linkedin:
          "https://www.linkedin.com/in/ansh-bishnoi-4b5b77386?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        github: null,
      },
      {
        name: "Aditya Jhajharia",
        photo: "/img/team/aditya-jhajharia.jpg",
        linkedin: null,
        github: null,
      },
      {
        name: "Aryan Singh",
        photo: "/img/team/aryan-singh.jpg",
        linkedin:
          "https://www.linkedin.com/in/aryan-singh-b7b20a385?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        github: "https://github.com/AryanSSSSSS",
      },
      {
        name: "Aviral Gupta",
        photo: "/img/team/aviral-gupta.jpg",
        linkedin:
          "https://www.linkedin.com/in/aviral-gupta-b9475a383?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: "https://github.com/aviralgupta4562-rgb",
      },
      {
        name: "Ayush Verma",
        photo: "/img/team/ayush-verma.jpg",
        linkedin: null,
        github: null,
      },
      {
        name: "Bulesh Thakur",
        photo: "/img/team/bulesh-thakur.jpg",
        linkedin:
          "https://www.linkedin.com/in/bulesh-thakur-ab48793a6?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: null,
      },
      {
        name: "Harshita",
        photo: "/img/team/harshita.jpg",
        linkedin:
          "https://www.linkedin.com/in/ms-harshita-3b41a7387?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: null,
      },
      {
        name: "Jeet Jeedan Behera",
        photo: "/img/team/jeet-jeedan-behera.jpg",
        linkedin: null,
        github: null,
      },
      {
        name: "Ketan",
        photo: "/img/team/ketan.png",
        linkedin:
          "https://www.linkedin.com/in/ketan-dadarwal-597583382?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app#",
        github: null,
      },
      {
        name: "Krishna Pratap Singh",
        photo: "/img/team/krishna-pratap-singh.jpg",
        linkedin:
          "https://www.linkedin.com/in/krishna-pratap-singh-8749983a2?utm_source=share&utm_campaign=share_via&utm_content=profile&utm_medium=android_app",
        github: null,
      },
      {
        name: "Kuldeep Bhakar",
        photo: null,
        linkedin: "https://www.linkedin.com/in/kuldeep-bhakar-976b10382",
        github: "https://github.com/kuldeep804",
      },
      {
        name: "Kush Sharma",
        photo: null,
        linkedin: null,
        github: null,
      },
      {
        name: "Kushagra Goel",
        photo: "/img/team/kushagra-goel.jpg",
        linkedin: "https://www.linkedin.com/in/kushagra-goel-6b8ab536a/",
        github: "https://github.com/kgoel17",
      },
      {
        name: "Neel Nalin Pathak",
        photo: "/img/team/neel-nalin-pathak.jpg",
        linkedin: null,
        github: null,
      },
      {
        name: "Priyanshu Saini",
        photo: "/img/team/priyanshu-saini.webp",
        linkedin: "https://www.linkedin.com/in/priyanshu-saini-4a13a0383/",
        github: "https://github.com/pr1y4nshusaini06-creator",
      },
      {
        name: "Rahul Sonkhla",
        photo: "/img/team/rahul-sonkhla.jpg",
        linkedin:
          "https://www.linkedin.com/in/rahul-sonkhla-b7a939379?utm_source=share_via&utm_content=profile&utm_medium=member_android",
        github: null,
      },
      {
        name: "Tanmay Rana",
        photo: "/img/team/tanmay-rana.jpg",
        linkedin: null,
        github: null,
      },
      {
        name: "Taniya Jorwal",
        photo: "/img/team/taniya-jorwal.webp",
        linkedin: "https://www.linkedin.com/in/taniya-jorwal-036004387",
        github: null,
      },
    ] as const
  ).map(
    (m, i): TeamMemberRecord => ({
      name: m.name,
      position: null,
      group: "EXECUTIVE",
      department: null,
      yearLabel: "First Year",
      bio: null,
      email: null,
      photo: m.photo,
      linkedin: m.linkedin,
      github: m.github,
      committee: false,
      draft: false,
      sortOrder: i,
    }),
  ),
];
